#!/usr/bin/env bash
# download_weights.sh — fetch the WBWAM base weights on a fresh machine.
#
# Nothing under checkpoints/ needs to be copied from another machine: every
# weight is either public on HuggingFace/ModelScope or generated by a script.
# This downloads them into $CKPT_DIR, laid out exactly how WBWAM's loader and
# README expect (see training/README.md and CLAUDE.md).
#
#   Public base model : Wan-AI/Wan2.2-TI2V-5B            (DiT backbone)
#   Tokenizer         : Wan-AI/Wan2.1-T2V-1.3B           (google/umt5-xxl only)
#   T5 encoder + VAE  : DiffSynth-Studio/Wan-Series-Converted-Safetensors (2 files)
#   ActionDiT backbone: generated locally from Wan22 DiT weights (optional)
#
# Usage:
#   scripts/migration/download_weights.sh                 # base weights, via hf-mirror
#   CKPT_DIR=/data/datasets/wbwam/checkpoints scripts/migration/download_weights.sh
#   HF_ENDPOINT=https://huggingface.co  ...               # use the main site (outside CN)
#   GEN_ACTIONDIT=1 ...                                   # also regenerate ActionDiT (needs a GPU)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Where weights land. Override CKPT_DIR to use a dedicated data disk.
CKPT_DIR="${CKPT_DIR:-$REPO_ROOT/training/checkpoints}"

# China mirror by default. Override to https://huggingface.co elsewhere.
export HF_ENDPOINT="${HF_ENDPOINT:-https://hf-mirror.com}"

GEN_ACTIONDIT="${GEN_ACTIONDIT:-0}"

# Pick a downloader CLI: prefer the new `hf`, fall back to `huggingface-cli`.
if command -v hf >/dev/null 2>&1; then
  DL() { hf download "$@"; }
elif command -v huggingface-cli >/dev/null 2>&1; then
  DL() { huggingface-cli download "$@"; }
else
  echo "ERROR: neither 'hf' nor 'huggingface-cli' found. pip install -U huggingface_hub" >&2
  exit 1
fi

echo "CKPT_DIR    = $CKPT_DIR"
echo "HF_ENDPOINT = $HF_ENDPOINT"
mkdir -p "$CKPT_DIR"

echo
echo "==> [1/3] Wan-AI/Wan2.2-TI2V-5B  (DiT backbone, ~19G)"
DL Wan-AI/Wan2.2-TI2V-5B --local-dir "$CKPT_DIR/Wan-AI/Wan2.2-TI2V-5B"

echo
echo "==> [2/3] Wan-AI/Wan2.1-T2V-1.3B  (umt5-xxl tokenizer only)"
DL Wan-AI/Wan2.1-T2V-1.3B --include 'google/umt5-xxl/*' \
   --local-dir "$CKPT_DIR/Wan-AI/Wan2.1-T2V-1.3B"

echo
echo "==> [3/3] DiffSynth-Studio T5 encoder + VAE  (2 files, ~12G)"
DL DiffSynth-Studio/Wan-Series-Converted-Safetensors \
   --include 'models_t5_umt5-xxl-enc-bf16.safetensors' 'Wan2.2_VAE.safetensors' \
   --local-dir "$CKPT_DIR/DiffSynth-Studio/Wan-Series-Converted-Safetensors"

if [ "$GEN_ACTIONDIT" = "1" ]; then
  echo
  echo "==> ActionDiT backbone: generating from Wan22 DiT weights (needs a GPU)"
  export DIFFSYNTH_MODEL_BASE_PATH="$CKPT_DIR"
  ( cd "$REPO_ROOT/training" && \
    python scripts/preprocess_action_dit_backbone.py \
      --model-config configs/model/wbwam_optional_idm.yaml \
      --output "$CKPT_DIR/ActionDiT_linear_interp_Wan22_alphascale_1024hdim.pt" \
      --device cuda --dtype bfloat16 )
else
  echo
  echo "NOTE: ActionDiT not generated. Run with GEN_ACTIONDIT=1 on a GPU node, or:"
  echo "  export DIFFSYNTH_MODEL_BASE_PATH=$CKPT_DIR"
  echo "  cd training && python scripts/preprocess_action_dit_backbone.py \\"
  echo "    --model-config configs/model/wbwam_optional_idm.yaml \\"
  echo "    --output $CKPT_DIR/ActionDiT_linear_interp_Wan22_alphascale_1024hdim.pt \\"
  echo "    --device cuda --dtype bfloat16"
fi

echo
echo "Done. Weights are under: $CKPT_DIR"
